### ISSUE TITLE
package.json 模板占位符替换的默认值问题

### ISSUE THREAD

**Issue by tinyhill** [midwayjs/light-generator#19]
https://github.com/midwayjs/light-generator/blob/2daea5981880a71b79cc81c97df765494c38e8e6/src/rule.ts#L62

这里，将匹配到的字符串 match 作为了默认值填充，假定初始化时未输入 description 值，会导致生成结果中仍然是 `{{description}}`，直接替换为空字符串是否更为合适？

**Comment by waitingsong** [comment]
如果的确是需要 输出双大括号包裹的字符串呢。

**Comment by czy88840616** [comment]
我理解这里适用于最小原则，只替换有值的部分，没值的部分保留原样，这样排查问题或者用户看到也能理解这里是个占位符，如果赋空值就不知道了。
